import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";
import { company } from "@/lib/data";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How ProjMan collects, uses, and protects personal information.",
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="1 September 2026">
      <p>
        {company.legalName} (&ldquo;ProjMan&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) respects
        your privacy. This policy explains what information we collect through this website and
        the ProjMan platform, how we use it, and the choices available to you.
      </p>
      <p>
        We collect information you provide directly — such as when you request a demo, start a
        trial, or contact us — and information generated by using the platform, including
        project, evidence, and verification records. We do not sell personal information.
      </p>
      <p>
        For any privacy questions or a request relating to your personal information, contact us
        at {company.email}.
      </p>
      <p className="text-navy-400">
        This is a summary placeholder. A full privacy policy will be published prior to public
        launch, reviewed against the Australian Privacy Act 1988 (Cth) and relevant state
        legislation.
      </p>
    </LegalPage>
  );
}
